"""
Django settings for skills_data project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from asyncio.log import logger
import os
from pathlib import Path

import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
CWD = Path(os.getcwd()).resolve()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s-!2)@8*71iq-gk86e^g#5o@j-ctz-zduiumzys3vf))hcpg11"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'rest_framework.authtoken',
    "adrf",
    'django_filters',
    "drf_spectacular",
    "corsheaders",
    "at_user_ng.apps.accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "at_user_ng.utils.middleware.initialization_check_middleware",
]

ROOT_URLCONF = "at_user_ng.base_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "at_user_ng.base_server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

sqlite_db_name_str = os.getenv("DB_NAME", str(CWD / "db.sqlite3"))
if not sqlite_db_name_str.endswith(".db") and not sqlite_db_name_str.endswith(".sqlite3"):
    sqlite_db_name_str += ".sqlite3"

sqlite_db_name = Path(sqlite_db_name_str)
if not sqlite_db_name.is_absolute():
    sqlite_db_name = CWD / sqlite_db_name


CORS_ALLOW_ALL_ORIGINS = True
CORS_EXPOSE_HEADERS = ['*']

logger.info('ENV DB ENGINE: %s', os.getenv("DB_ENGINE"))


SQLITE_CONFIG = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": sqlite_db_name,
}

POSTGRES_CONFIG = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": os.getenv("DB_NAME", "at_user"),
    "USER": os.getenv("DB_USER", "at_user"),
    "PASSWORD": os.getenv("DB_PASS"),
    "HOST": os.getenv("DB_HOST", "postgres"),
    "PORT": os.getenv("DB_PORT", "5432"),
}

db_engine = os.getenv("DB_ENGINE")

default_db = {"postgres": POSTGRES_CONFIG, "sqlite": SQLITE_CONFIG}[db_engine]

DATABASES = {"default": default_db}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "at_user_ng.base_server.autoschema.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "AT_USER_NG",
    "DESCRIPTION": "API for users and auth",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r'/api/',
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
